version: '3'

networks:
  traefik_default:
    external: true

services:
  images_internal:
    networks:
      - traefik_default
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.shiro-internal.rule=Host(`internal.dbot.dev`) && Path(`/images`)
      - traefik.http.routers.shiro-internal.entrypoints=web
      - traefik.http.services.shiro-internal.loadbalancer.server.port=5400