version: '3'

networks:
  backend:
    external: true
  traefik_default:
    external: true

services:
  images_internal:
    networks:
      - traefik_default
      - backend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/data
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.shiro-internal.stripprefix.prefixes=/images
      - traefik.http.middlewares.shiro-internal.stripprefix.forceSlash=false
      - traefik.http.routers.shiro-internal.rule=Host(`internal.dbot.dev`) && PathPrefix(`/images/`)
      - traefik.http.routers.shiro-internal.middlewares=shiro-internal@docker
      - traefik.http.routers.shiro-internal.entrypoints=web
      - traefik.http.services.shiro-internal.loadbalancer.server.port=5400
