version: '3'

services:
  images_internal:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shiro-intenal.rule=Host(`internal.dbot.dev`)"
      - "traefik.http.routers.shiro-intenal.entrypoints=web"